import { BuilderElement, ElementType, StyleProperties } from '../types/builder';
import { generateId } from './builderUtils';

/**
 * Converts HTML string generated by Gemini into a BuilderElement tree
 */
export const htmlToBuilderElements = (
  htmlContent: string,
  parentId: string | null = null
): BuilderElement[] => {
  try {
    // Create a temporary container to parse HTML
    const temp = document.createElement('div');
    temp.innerHTML = htmlContent;

    applyStyleTagRules(temp);

    const elements: BuilderElement[] = [];

    // Process each child node
    temp.childNodes.forEach((node) => {
      const element = nodeToBuilderElement(node, parentId);
      if (element) {
        elements.push(element);
      }
    });

    return elements;
  } catch (error) {
    console.error('Error converting HTML to builder elements:', error);
    // Return a fallback element with the HTML content
    return [
      {
        id: generateId(),
        type: 'section',
        name: 'Generated Content',
        props: { innerHTML: htmlContent },
        styles: {
          widescreen: {},
          desktop: {
            display: 'flex',
            flexDirection: 'column',
            width: '100%',
            padding: '20px',
          },
          tablet: {},
          mobile: {},
          laptop: {},
          mobileLandscape: {},
        },
        children: [],
        parentId,
        locked: false,
        hidden: false,
      },
    ];
  }
};

/**
 * Converts a DOM node to a BuilderElement
 */
const nodeToBuilderElement = (
  node: Node,
  parentId: string | null
): BuilderElement | null => {
  // Skip text nodes that are just whitespace
  if (node.nodeType === Node.TEXT_NODE) {
    const text = node.textContent?.trim();
    if (!text) return null;

    return {
      id: generateId(),
      type: 'paragraph',
      name: 'Text',
      props: { text },
      styles: {
        widescreen: {},
        desktop: {},
        tablet: {},
        mobile: {},
        laptop: {},
        mobileLandscape: {},
      },
      children: [],
      parentId,
      locked: false,
      hidden: false,
    };
  }

  if (node.nodeType !== Node.ELEMENT_NODE) return null;

  const element = node as HTMLElement;
  const tagName = element.tagName.toLowerCase();

  // Map HTML tags to builder element types
  const elementType = mapHtmlTagToElementType(tagName);
  if (!elementType) return null;

  const builderId = generateId();

  // Extract inline styles
  const styles = extractStylesFromElement(element);

  // Extract text content and props
  const props = extractPropsFromElement(element, tagName);

  // Process children
  const children: BuilderElement[] = [];
  element.childNodes.forEach((childNode) => {
    const child = nodeToBuilderElement(childNode, builderId);
    if (child) {
      children.push(child);
    }
  });

  return {
    id: builderId,
    type: elementType,
    name: getElementName(elementType),
    props,
    styles: {
      widescreen: {},
      desktop: styles,
      tablet: {},
      mobile: {},
      laptop: {},
      mobileLandscape: {},
    },
    children,
    parentId,
    locked: false,
    hidden: false,
  };
};

/**
 * Maps HTML tags to builder element types
 */
const mapHtmlTagToElementType = (tagName: string): ElementType | null => {
  const tagMap: Record<string, ElementType> = {
    section: 'section',
    div: 'div',
    main: 'section',
    article: 'section',
    aside: 'section',
    nav: 'navbar',
    h1: 'heading',
    h2: 'heading',
    h3: 'heading',
    h4: 'heading',
    h5: 'heading',
    h6: 'heading',
    p: 'paragraph',
    a: 'link',
    button: 'button',
    img: 'image',
    video: 'video',
    ul: 'list',
    ol: 'list',
    li: 'listItem',
    form: 'form',
    input: 'input',
    textarea: 'textarea',
    hr: 'divider',
    iframe: 'iframe',
  };

  return tagMap[tagName] || null;
};

/**
 * Extracts CSS styles from element's style attribute
 */
const extractStylesFromElement = (element: HTMLElement): StyleProperties => {
  const styles: StyleProperties = {};
  const style = element.getAttribute('style');

  if (!style) return styles;

  // Parse inline styles
  style.split(';').forEach((rule) => {
    const trimmedRule = rule.trim();
    if (!trimmedRule) return;

    const colonIndex = trimmedRule.indexOf(':');
    if (colonIndex === -1) return;

    const property = trimmedRule.slice(0, colonIndex).trim();
    const value = trimmedRule.slice(colonIndex + 1).trim();
    if (property && value) {
      // Convert CSS property names to camelCase
      const camelProperty = cssPropertyToCamel(property);
      (styles as any)[camelProperty] = value;
    }
  });

  return styles;
};

const applyStyleTagRules = (container: HTMLElement): void => {
  const styleTags = Array.from(container.querySelectorAll('style'));

  styleTags.forEach((styleTag) => {
    const cssText = styleTag.textContent || '';
    const rules = parseCssRules(cssText);

    rules.forEach(({ selector, declarations }) => {
      try {
        const matched = Array.from(container.querySelectorAll(selector));
        matched.forEach((matchedNode) => {
          if (!(matchedNode instanceof HTMLElement)) return;
          const currentStyles = extractStylesFromElement(matchedNode);
          const mergedStyles = { ...currentStyles, ...declarations };
          matchedNode.setAttribute('style', styleObjectToString(mergedStyles));
        });
      } catch (error) {
        console.warn('Could not apply style selector:', selector, error);
      }
    });

    styleTag.remove();
  });
};

const parseCssRules = (cssText: string): Array<{ selector: string; declarations: StyleProperties }> => {
  const cleaned = cssText.replace(/\/\*[\s\S]*?\*\//g, '');
  const rules: Array<{ selector: string; declarations: StyleProperties }> = [];
  const regex = /([^{}]+)\{([^}]+)\}/g;
  let match: RegExpExecArray | null;

  while ((match = regex.exec(cleaned)) !== null) {
    const selector = match[1].trim();
    const declarationsText = match[2].trim();
    if (!selector || selector.startsWith('@')) continue;
    const declarations = parseCssDeclarations(declarationsText);
    if (Object.keys(declarations).length > 0) {
      rules.push({ selector, declarations });
    }
  }

  return rules;
};

const parseCssDeclarations = (declarationsText: string): StyleProperties => {
  const declarations: StyleProperties = {};

  declarationsText.split(';').forEach((rule) => {
    const trimmedRule = rule.trim();
    if (!trimmedRule) return;

    const colonIndex = trimmedRule.indexOf(':');
    if (colonIndex === -1) return;

    const property = trimmedRule.slice(0, colonIndex).trim();
    let value = trimmedRule.slice(colonIndex + 1).trim();
    if (value.endsWith('!important')) {
      value = value.replace(/!important$/, '').trim();
    }

    if (property && value) {
      const camelProperty = cssPropertyToCamel(property);
      (declarations as any)[camelProperty] = value;
    }
  });

  return declarations;
};

const styleObjectToString = (styles: StyleProperties): string => {
  return Object.entries(styles)
    .filter(([, value]) => value !== undefined && value !== null && value !== '')
    .map(([key, value]) => `${key.replace(/[A-Z]/g, match => `-${match.toLowerCase()}`)}: ${value}`)
    .join('; ');
};

/**
 * Converts CSS property names (kebab-case) to camelCase
 */
const cssPropertyToCamel = (property: string): string => {
  return property.replace(/-([a-z])/g, (_, letter) => letter.toUpperCase());
};

/**
 * Extracts element props from HTML attributes
 */
const extractPropsFromElement = (element: HTMLElement, tagName: string): Record<string, any> => {
  const props: Record<string, any> = {};

  if (tagName === 'a') {
    props.href = element.getAttribute('href') || '#';
    props.text = element.textContent || 'Link';
  } else if (tagName === 'button') {
    props.text = element.textContent || 'Button';
    props.href = element.getAttribute('onclick') || '#';
  } else if (tagName === 'img') {
    props.src = element.getAttribute('src') || '';
    props.alt = element.getAttribute('alt') || 'Image';
  } else if (tagName === 'input') {
    props.type = element.getAttribute('type') || 'text';
    props.placeholder = element.getAttribute('placeholder') || '';
  } else if (['h1', 'h2', 'h3', 'h4', 'h5', 'h6'].includes(tagName)) {
    props.text = element.textContent || 'Heading';
    props.level = parseInt(tagName[1], 10);
  } else if (tagName === 'p') {
    props.text = element.textContent || '';
  } else if (tagName === 'li') {
    props.text = element.textContent || '';
  } else if (tagName === 'video') {
    props.src = element.getAttribute('src') || element.querySelector('source')?.getAttribute('src') || '';
    props.autoplay = element.hasAttribute('autoplay');
    props.controls = element.hasAttribute('controls');
  } else if (tagName === 'iframe') {
    props.src = element.getAttribute('src') || '';
    props.title = element.getAttribute('title') || 'Embedded Content';
  }

  return props;
};

/**
 * Gets a friendly name for an element type
 */
const getElementName = (type: ElementType): string => {
  const names: Record<ElementType, string> = {
    section: 'Section',
    div: 'Container',
    heading: 'Heading',
    paragraph: 'Paragraph',
    button: 'Button',
    image: 'Image',
    link: 'Link',
    navbar: 'Navigation',
    hero: 'Hero',
    card: 'Card',
    grid: 'Grid',
    columns: 'Columns',
    form: 'Form',
    input: 'Input',
    textarea: 'Textarea',
    video: 'Video',
    divider: 'Divider',
    spacer: 'Spacer',
    icon: 'Icon',
    list: 'List',
    listItem: 'List Item',
    iframe: 'Embedded Content',
  };

  return names[type] || 'Element';
};
