import { BuilderElement, Page } from '../types/builder';
import { generateId } from './builderUtils';

export const createStarterPage = (): Page => {
  const navId = generateId();
  const heroId = generateId();
  const featuresId = generateId();
  const card1Id = generateId();
  const card2Id = generateId();
  const card3Id = generateId();
  const ctaId = generateId();

  const elements: BuilderElement[] = [
    // Navbar
    {
      id: navId,
      type: 'navbar',
      name: 'Navigation',
      props: {},
      styles: {
        desktop: {
          display: 'flex',
          alignItems: 'center',
          justifyContent: 'space-between',
          width: '100%',
          padding: '20px 60px',
          backgroundColor: '#ffffff',
          boxShadow: '0 1px 0 rgba(0,0,0,0.06)',
          position: 'sticky',
          top: '0',
          zIndex: '100',
        },
        tablet: { padding: '16px 32px' },
        mobile: { padding: '12px 16px' },
        widescreen: {
          display: 'flex',
          alignItems: 'center',
          justifyContent: 'space-between',
          width: '100%',
          padding: '20px 80px',
          backgroundColor: '#ffffff',
          boxShadow: '0 1px 0 rgba(0,0,0,0.06)',
          position: 'sticky',
          top: '0',
          zIndex: '100',
        },
        laptop: {
          display: 'flex',
          alignItems: 'center',
          justifyContent: 'space-between',
          width: '100%',
          padding: '20px 60px',
          backgroundColor: '#ffffff',
          boxShadow: '0 1px 0 rgba(0,0,0,0.06)',
          position: 'sticky',
          top: '0',
          zIndex: '100',
        },
        mobileLandscape: { padding: '12px 24px' },
      },
      children: [
        {
          id: generateId(),
          type: 'heading',
          name: 'Logo',
          props: { text: 'Acme Co.', level: 3 },
          styles: {
            desktop: { fontSize: '22px', fontWeight: '700', color: '#0f172a', margin: '0' },
            tablet: {},
            mobile: {},
            widescreen: { fontSize: '22px', fontWeight: '700', color: '#0f172a', margin: '0' },
            laptop: { fontSize: '22px', fontWeight: '700', color: '#0f172a', margin: '0' },
            mobileLandscape: { fontSize: '22px', fontWeight: '700', color: '#0f172a', margin: '0' },
          },
          children: [],
          parentId: navId,
          locked: false,
          hidden: false,
        },
        {
          id: generateId(),
          type: 'div',
          name: 'Nav Links',
          props: {},
          styles: {
            desktop: { display: 'flex', alignItems: 'center', gap: '32px' },
            tablet: { display: 'none' },
            mobile: { display: 'none' },
            widescreen: { display: 'flex', alignItems: 'center', gap: '32px' },
            laptop: { display: 'flex', alignItems: 'center', gap: '32px' },
            mobileLandscape: { display: 'none' },
          },
          children: [
            { id: generateId(), type: 'link', name: 'Features', props: { text: 'Features', href: '#' }, styles: { desktop: { color: '#64748b', fontSize: '15px', textDecoration: 'none', fontWeight: '500' }, tablet: {}, mobile: {}, widescreen: {}, laptop: {}, mobileLandscape: {} }, children: [], parentId: null, locked: false, hidden: false },
            { id: generateId(), type: 'link', name: 'Pricing', props: { text: 'Pricing', href: '#' }, styles: { desktop: { color: '#64748b', fontSize: '15px', textDecoration: 'none', fontWeight: '500' }, tablet: {}, mobile: {}, widescreen: {}, laptop: {}, mobileLandscape: {} }, children: [], parentId: null, locked: false, hidden: false },
            { id: generateId(), type: 'link', name: 'About', props: { text: 'About', href: '#' }, styles: { desktop: { color: '#64748b', fontSize: '15px', textDecoration: 'none', fontWeight: '500' }, tablet: {}, mobile: {}, widescreen: {}, laptop: {}, mobileLandscape: {} }, children: [], parentId: null, locked: false, hidden: false },
          ],
          parentId: navId,
          locked: false,
          hidden: false,
        },
        {
          id: generateId(),
          type: 'icon',
          name: 'Hamburger',
          props: { iconName: 'Menu' },
          styles: {
            desktop: { display: 'none', cursor: 'pointer', width: '40px', height: '40px', alignItems: 'center', justifyContent: 'center', color: '#0f172a' },
            tablet: { display: 'flex' },
            mobile: { display: 'flex' },
            widescreen: { display: 'none' },
            laptop: { display: 'none' },
            mobileLandscape: { display: 'flex' },
          },
          children: [],
          parentId: navId,
          locked: false,
          hidden: false,
        },
        {
          id: generateId(),
          type: 'button',
          name: 'CTA Button',
          props: { text: 'Get Started', href: '#' },
          styles: {
            desktop: {
              display: 'inline-flex',
              alignItems: 'center',
              padding: '10px 24px',
              backgroundColor: '#2563eb',
              color: '#ffffff',
              fontSize: '14px',
              fontWeight: '600',
              borderRadius: '8px',
              border: 'none',
              cursor: 'pointer',
            },
            tablet: {},
            mobile: {},
            widescreen: {},
            laptop: {},
            mobileLandscape: {},
          },
          children: [],
          parentId: navId,
          locked: false,
          hidden: false,
        },
      ],
      parentId: null,
      locked: false,
      hidden: false,
    },

    // Hero
    {
      id: heroId,
      type: 'hero',
      name: 'Hero Section',
      props: {},
      styles: {
        desktop: {
          display: 'flex',
          flexDirection: 'column',
          alignItems: 'center',
          justifyContent: 'center',
          width: '100%',
          minHeight: '680px',
          padding: '100px 60px',
          backgroundImage: 'linear-gradient(135deg, #f0f9ff 0%, #e0f2fe 50%, #f0f4ff 100%)',
          textAlign: 'center',
        },
        tablet: { padding: '80px 32px', minHeight: '560px' },
        mobile: { padding: '60px 16px', minHeight: '480px' },
        widescreen: { padding: '100px 60px', minHeight: '680px' },
        laptop: { padding: '100px 60px', minHeight: '680px' },
        mobileLandscape: { padding: '60px 24px', minHeight: '480px' },
      },
      children: [
        {
          id: generateId(),
          type: 'paragraph',
          name: 'Badge',
          props: { text: '✨ Now with AI-powered features' },
          styles: {
            desktop: {
              display: 'inline-block',
              padding: '6px 16px',
              backgroundColor: '#dbeafe',
              color: '#1d4ed8',
              fontSize: '13px',
              fontWeight: '600',
              borderRadius: '100px',
              marginBottom: '24px',
              letterSpacing: '0.02em',
            },
            tablet: {},
            mobile: {},
            widescreen: {},
            laptop: {},
            mobileLandscape: { display: 'none' },
          },
          children: [],
          parentId: heroId,
          locked: false,
          hidden: false,
        },
        {
          id: generateId(),
          type: 'heading',
          name: 'Hero Title',
          props: { text: 'Build beautiful websites in minutes', level: 1 },
          styles: {
            desktop: {
              fontSize: '64px',
              fontWeight: '800',
              lineHeight: '1.1',
              color: '#0f172a',
              maxWidth: '760px',
              marginBottom: '24px',
              letterSpacing: '-0.03em',
            },
            tablet: { fontSize: '44px' },
            mobile: { fontSize: '32px', letterSpacing: '-0.02em' },
            widescreen: { fontSize: '64px', letterSpacing: '-0.03em' },
            laptop: { fontSize: '64px', letterSpacing: '-0.03em' },
            mobileLandscape: { fontSize: '36px', letterSpacing: '-0.02em' },
          },
          children: [],
          parentId: heroId,
          locked: false,
          hidden: false,
        },
        {
          id: generateId(),
          type: 'paragraph',
          name: 'Hero Subtitle',
          props: { text: 'The most intuitive drag-and-drop builder for creating stunning websites. No coding required. Launch in minutes.' },
          styles: {
            desktop: {
              fontSize: '20px',
              lineHeight: '1.6',
              color: '#64748b',
              maxWidth: '560px',
              marginBottom: '40px',
            },
            tablet: { fontSize: '18px' },
            mobile: { fontSize: '16px' },
            widescreen: { fontSize: '20px' },
            laptop: { fontSize: '20px' },
            mobileLandscape: { fontSize: '18px' },
          },
          children: [],
          parentId: heroId,
          locked: false,
          hidden: false,
        },
        {
          id: generateId(),
          type: 'div',
          name: 'Hero Buttons',
          props: {},
          styles: {
            desktop: { display: 'flex', gap: '16px', justifyContent: 'center', flexWrap: 'wrap' },
            tablet: {},
            mobile: { flexDirection: 'column', alignItems: 'center' },
            widescreen: { display: 'flex', gap: '16px', justifyContent: 'center', flexWrap: 'wrap' },
            laptop: { display: 'flex', gap: '16px', justifyContent: 'center', flexWrap: 'wrap' },
            mobileLandscape: { flexDirection: 'column', alignItems: 'center' },
          },
          children: [
            {
              id: generateId(),
              type: 'button',
              name: 'Primary CTA',
              props: { text: 'Start building for free', href: '#' },
              styles: {
                desktop: {
                  display: 'inline-flex',
                  alignItems: 'center',
                  padding: '16px 32px',
                  backgroundColor: '#2563eb',
                  color: '#ffffff',
                  fontSize: '16px',
                  fontWeight: '600',
                  borderRadius: '10px',
                  border: 'none',
                  cursor: 'pointer',
                  boxShadow: '0 4px 14px rgba(37,99,235,0.4)',
                },
                tablet: {},
                mobile: {},
                widescreen: {},
                laptop: {},
                mobileLandscape: {},
              },
              children: [],
              parentId: null,
              locked: false,
              hidden: false,
            },
            {
              id: generateId(),
              type: 'button',
              name: 'Secondary CTA',
              props: { text: 'View examples', href: '#' },
              styles: {
                desktop: {
                  display: 'inline-flex',
                  alignItems: 'center',
                  padding: '16px 32px',
                  backgroundColor: 'transparent',
                  color: '#374151',
                  fontSize: '16px',
                  fontWeight: '600',
                  borderRadius: '10px',
                  border: '1.5px solid #d1d5db',
                  cursor: 'pointer',
                },
                tablet: {},
                mobile: {},
                widescreen: {},
                laptop: {},
                mobileLandscape: {},
              },
              children: [],
              parentId: null,
              locked: false,
              hidden: false,
            },
          ],
          parentId: heroId,
          locked: false,
          hidden: false,
        },
      ],
      parentId: null,
      locked: false,
      hidden: false,
    },

    // CTA Section
    {
      id: ctaId,
      type: 'section',
      name: 'CTA Section',
      props: {},
      styles: {
        desktop: {
          display: 'flex',
          flexDirection: 'column',
          alignItems: 'center',
          justifyContent: 'center',
          width: '100%',
          padding: '100px 60px',
          backgroundImage: 'linear-gradient(135deg, #1e40af 0%, #2563eb 100%)',
          textAlign: 'center',
        },
        tablet: { padding: '80px 32px' },
        mobile: { padding: '60px 16px' },
        widescreen: { padding: '100px 60px' },
        laptop: { padding: '100px 60px' },
        mobileLandscape: { padding: '60px 24px' },
      },
      children: [
        {
          id: generateId(),
          type: 'heading',
          name: 'CTA Title',
          props: { text: 'Ready to get started?', level: 2 },
          styles: {
            desktop: { fontSize: '48px', fontWeight: '800', color: '#ffffff', marginBottom: '20px', letterSpacing: '-0.02em' },
            tablet: { fontSize: '36px' },
            mobile: { fontSize: '28px' },
            widescreen: { fontSize: '48px', letterSpacing: '-0.03em' },
            laptop: { fontSize: '48px', letterSpacing: '-0.03em' },
            mobileLandscape: { fontSize: '36px' },
          },
          children: [],
          parentId: ctaId,
          locked: false,
          hidden: false,
        },
        {
          id: generateId(),
          type: 'paragraph',
          name: 'CTA Subtitle',
          props: { text: 'Join over 100,000 creators building with Forge today.' },
          styles: {
            desktop: { fontSize: '18px', color: 'rgba(255,255,255,0.8)', marginBottom: '40px', lineHeight: '1.6' },
            tablet: {},
            mobile: { fontSize: '16px' },
            widescreen: { fontSize: '20px' },
            laptop: { fontSize: '20px' },
            mobileLandscape: { fontSize: '18px' },
          },
          children: [],
          parentId: ctaId,
          locked: false,
          hidden: false,
        },
        {
          id: generateId(),
          type: 'button',
          name: 'CTA Button',
          props: { text: 'Start for free — no credit card', href: '#' },
          styles: {
            desktop: {
              display: 'inline-flex',
              alignItems: 'center',
              padding: '16px 36px',
              backgroundColor: '#ffffff',
              color: '#1e40af',
              fontSize: '16px',
              fontWeight: '700',
              borderRadius: '10px',
              border: 'none',
              cursor: 'pointer',
              boxShadow: '0 4px 24px rgba(0,0,0,0.2)',
            },
            tablet: {},
            mobile: {},
            widescreen: { padding: '16px 36px', fontSize: '18px' },
            laptop: { padding: '16px 36px', fontSize: '18px' },
            mobileLandscape: { padding: '16px 36px', fontSize: '18px' },
          },
          children: [],
          parentId: ctaId,
          locked: false,
          hidden: false,
        },
      ],
      parentId: null,
      locked: false,
      hidden: false,
    },
  ];

  return {
    id: 'page-1',
    name: 'Home',
    slug: '/',
    elements,
    seo: {
      title: 'My Website',
      description: 'A beautiful website built with Forge',
      keywords: 'website, builder, forge',
    },
  };
};
