export const GOOGLE_FONT_OPTIONS = [
  'Arial',
  'Helvetica',
  'Roboto, sans-serif',
  'Open Sans',
  'Lato',
  'Montserrat',
  'Poppins',
  'Inter',
  'Oswald',
  'Source Sans',
  'Nunito',
  'Raleway',
  'Work Sans',
  'Ubuntu',
  'Fira Sans',
  'Karla',
  'DM Sans',
  'Hind',
  'Oxygen',
  'Quicksand',
  'Muli',
  'Cabin',
  'Josefin Sans',
  'Space Grotesk',
  'Nunito Sans',
  'Sora',
  'Manrope',
  'Mukta',
  'Bai Jamjuree',
  'Lexend',
  'Cairo',
  'Tajawal',
  'Heebo',
  'Anton',
  'Bebas Neue',
  'Merriweather',
  'Roboto Slab',
  'Noto Serif',
  'Spectral',
  'PT Serif',
  'Domine',
  'Crimson Pro',
  'Cardo',
  'Pacifico',
  'Dancing Script',
  'Great Vibes',
  'Satisfy',
  'Amatic SC',
  'Bangers',
  'Yellowtail',
  'Lobster',
  'Roboto Mono',
  'Fira Code',
  'Source Code Pro',
  'JetBrains Mono',
  'Space Mono',
  'Inconsolata',
  'Courier Prime',
];